#!/usr/bin/env bash
#Writing a Bash script that configures an Ubuntu server with
#localhost to 127.0.0.2
#facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost$/127.0.0.2\n8.8.8.8 facebook.com ~hosts.new
cp -f ~/hosts.new /etc/hosts
